#!/usr/bin/env python3
"""build-badge-imgs.py — generate js/badge-imgs.js

Every club the game can name gets one badge, embedded as a data URI. Each is
trimmed of its transparent margin, re-padded evenly, sized to a fixed height
and palette-reduced, so the whole set is one consistent format and about a
quarter of the bytes a full-colour PNG would cost. Nothing is fetched at
runtime — crest.js draws no fallback shield, and build.js fails if a club in
data.js or a player's timeline has no badge here.

Badges are read from local checkouts of public logo collections rather than
hotlinked, so a build is reproducible and the game never waits on a request.
Clone the sources listed in SOURCES, then run from the repo root:

    python3 tools/build-badge-imgs.py

Re-running is safe: a club already in js/badge-imgs.js keeps its badge unless
SOURCES names a file for it, so the set only ever grows or gets replaced
deliberately.
"""
import base64
import io
import json
import os
import re
import sys

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'js', 'badge-imgs.js')
HEIGHT = 144        # 2x+ the biggest display size (.crest-xl = 64px)
COLORS = 255        # palette size; the 256th slot is transparency

# Where the logo checkouts live. Override with BADGE_SRC_<KEY> in the
# environment if yours are somewhere else.
SOURCES = {
    'luuk':   '/home/user/luukhopman/football-logos',   # github.com/luukhopman/football-logos
    'fclogo': '/home/user/fclogo',                      # github.com/FCLOGO/fclogo.top
    'ligamx': '/home/user/ligamx',                      # github.com/david0malr/Logos-Liga-MX
    'escudo': '/home/user/escudos',                     # github.com/damiansilvero/EscudosLigaMX
}
# club name -> path relative to one of the SOURCES roots, as "<key>:<path>"
MAP = os.path.join(ROOT, 'tools', 'badge-sources.json')


def root(key):
    return os.environ.get('BADGE_SRC_' + key.upper(), SOURCES[key])


def resolve(spec):
    key, rel = spec.split(':', 1)
    return os.path.join(root(key), rel)


def normalise(img):
    """Trim the transparent margin, re-pad evenly, size to a fixed height."""
    if img.getchannel('A').getextrema()[0] == 255:
        # a source with no transparency at all: drop a white background
        px = img.load()
        w, h = img.size
        corners = [px[0, 0], px[w - 1, 0], px[0, h - 1], px[w - 1, h - 1]]
        if all(c[0] > 235 and c[1] > 235 and c[2] > 235 for c in corners):
            img.putdata([(r, g, b, 0) if (r > 238 and g > 238 and b > 238) else (r, g, b, a)
                         for (r, g, b, a) in img.getdata()])
    bbox = img.getchannel('A').getbbox()
    if bbox:
        img = img.crop(bbox)
    w, h = img.size
    pad = max(3, int(max(w, h) * 0.04))
    canvas = Image.new('RGBA', (w + pad * 2, h + pad * 2), (0, 0, 0, 0))
    canvas.paste(img, (pad, pad))
    ratio = HEIGHT / canvas.size[1]
    return canvas.resize((max(1, round(canvas.size[0] * ratio)), HEIGHT), Image.LANCZOS)


def encode(im):
    buf = io.BytesIO()
    im.save(buf, 'PNG', optimize=True)
    return buf.getvalue()


def compress(im):
    """Displayed at 64px or less, a 255-colour palette is indistinguishable
    from the full-colour original and roughly a quarter of the bytes."""
    small = encode(im.quantize(colors=COLORS, method=Image.FASTOCTREE,
                               dither=Image.FLOYDSTEINBERG))
    full = encode(im)
    return small if len(small) < len(full) else full


def load_existing():
    if not os.path.exists(OUT):
        return {}
    src = open(OUT, encoding='utf-8').read()
    m = re.search(r'global\.BADGE_IMGS = (\{[\s\S]*?\});\n', src)
    return json.loads(m.group(1)) if m else {}


def main():
    out = load_existing()
    kept = len(out)
    sources = json.load(open(MAP, encoding='utf-8'))
    built = 0
    for club in sorted(sources):
        path = resolve(sources[club])
        if not os.path.exists(path):
            sys.exit('missing source for %s: %s' % (club, path))
        data = compress(normalise(Image.open(path).convert('RGBA')))
        out[club] = 'data:image/png;base64,' + base64.b64encode(data).decode('ascii')
        built += 1

    body = ',\n'.join('  %s: %s' % (json.dumps(k, ensure_ascii=False), json.dumps(out[k]))
                      for k in sorted(out))
    head = '''/* ==========================================================================
   badge-imgs.js — GENERATED by tools/build-badge-imgs.py. Do not edit.

   Every club in the game, one badge each: trimmed of its transparent margin,
   centred, sized to a fixed height and palette-reduced, then embedded as a
   data URI. Nothing is fetched at runtime, so a badge can never fail to load
   and there is no hotlink to go stale — which is why crest.js draws no
   fallback shield any more.
   ========================================================================== */
(function (global) {
  'use strict';
  global.BADGE_IMGS = {
'''
    open(OUT, 'w', encoding='utf-8').write(head + body + '\n};\n})(window);\n')
    print('js/badge-imgs.js written — %d badges (%d rebuilt, %d carried over)'
          % (len(out), built, kept - built if kept > built else 0))


if __name__ == '__main__':
    main()
