#!/usr/bin/env python3
"""build-trophy-imgs.py — generate js/trophy-imgs.js

Takes the best available photo of each trophy, removes the background with
rembg (bria-rmbg), trims to the subject and ships the result as a transparent
PNG data URI inside the game itself — no hotlink, works offline, no museum
display case in the frame. Run from the repo root:

    .venv/Scripts/python tools/build-trophy-imgs.py

Sources stay credited as hotlink fallbacks in js/trophies.js.
"""
import base64
import io
import json
import os
import sys
import urllib.request

from PIL import Image
from rembg import remove

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STAGE = os.path.join(ROOT, '.tmp-trophies')
OUT = os.path.join(ROOT, 'js', 'trophy-imgs.js')
UA = {'User-Agent': 'FootballLifeGame/1.0 (trophy image builder; local dev)'}
WMC = 'https://upload.wikimedia.org/wikipedia/commons'

# id -> (source URL, optional pre-crop as (left, top, right, bottom) fractions)
# Crops cut team-mates, shirts and signage out of frame before bg removal.
SOURCES = {
    'worldcup':    (WMC + '/c/ce/FIFA_World_Cup_Trophy_photo_by_Djuradj_Vujcic.jpg', None),
    'euros':       (WMC + '/8/81/Coupe_Henri_Delaunay_2017.jpg', None),
    'copaamerica': (WMC + '/9/97/Copa_america_trofeo.jpg', None),
    'ucl':         (WMC + '/1/18/Coppacampioni_%28closer%29.png', None),
    'uel':         (WMC + '/4/42/Europa_league_trophy.jpg', (0.42, 0.0, 1.0, 1.0)),
    'libertadores':(WMC + '/7/7a/328-3287452_copa-libertadores-primer-trofeo-hd-png-download.png', None),
    'concacaf':    (WMC + '/thumb/d/de/CONCACAF_Champions_League_Cup.svg/330px-CONCACAF_Champions_League_Cup.svg.png', None),
    'pl':          (WMC + '/f/f2/Premier_League_Trophy_at_Manchester%27s_National_Football_Museum_%28Ank_Kumar%29_01.jpg', (0.18, 0.0, 0.82, 1.0)),
    'laliga':      (WMC + '/d/d3/Trofeo_de_La_Liga_9900.jpg', None),
    'seriea':      (WMC + '/a/ae/Coppa_Campioni_d%27Italia_%28Serie_A%29.png', None),
    'bundesliga':  (WMC + '/f/f9/Trophy_of_Fu%C3%9Fball-Bundesliga_in_Singapore%2C_2023.jpg', None),
    'ligue1':      (WMC + '/5/5a/Hexagoal.jpg', (0.20, 0.08, 0.80, 0.82)),
    'facup':       (WMC + '/3/3f/The_FA_Cup_Trophy.jpg', None),
    'copadelrey':  (WMC + '/a/a4/Copa_del_Rey_Trophy.png', None),
    'coppaitalia': (WMC + '/2/29/Coppa_Italia_trophy_icon.jpg', None),
    'dfbpokal':    (WMC + '/d/d8/DFB_Pokal_Trophy.png', None),
    'coupefrance': (WMC + '/1/1f/Coupe_de_France_trophy.png', None),
    'knvb':        (WMC + '/d/d2/Gouden_KNVB_beker.png', None),
    'taca':        (WMC + '/7/70/Ta%C3%A7a_de_Portugal_Trophy.png', None),
    'ballondor':   (WMC + '/0/04/2016_Ballon_dOr_CR7Museum.jpg', None),
    'goldenshoe':  ('https://upload.wikimedia.org/wikipedia/en/2/2b/Golden_Shoe%2C_Lionel_Messi_2012-2013.jpg', None),
}

HEIGHT = 256  # px, plenty for a cabinet slot at 2x DPR


def fetch(url):
    req = urllib.request.Request(url, headers=UA)
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read()


def process(raw, crop):
    img = Image.open(io.BytesIO(raw)).convert('RGBA')
    if crop:
        w, h = img.size
        img = img.crop((int(w * crop[0]), int(h * crop[1]), int(w * crop[2]), int(h * crop[3])))
    img = remove(img)  # rembg: alpha matting onto transparency
    # trim to the subject
    bbox = img.getchannel('A').getbbox()
    if bbox:
        img = img.crop(bbox)
    # a little breathing room, then scale down
    w, h = img.size
    pad = max(4, int(max(w, h) * 0.03))
    canvas = Image.new('RGBA', (w + pad * 2, h + pad * 2), (0, 0, 0, 0))
    canvas.paste(img, (pad, pad))
    ratio = HEIGHT / canvas.size[1]
    canvas = canvas.resize((max(1, int(canvas.size[0] * ratio)), HEIGHT), Image.LANCZOS)
    buf = io.BytesIO()
    canvas.save(buf, 'PNG', optimize=True)
    return canvas, buf.getvalue()


def main():
    os.makedirs(STAGE, exist_ok=True)
    # optional id filter: reprocess just these (e.g. after fixing a source);
    # the JS is always emitted from every staged PNG, so partial runs are fine
    only = set(sys.argv[1:])
    for tid, (url, crop) in SOURCES.items():
        if only and tid not in only:
            continue
        try:
            img, png = process(fetch(url), crop)
            img.save(os.path.join(STAGE, tid + '.png'))
            print(f'{tid}: staged {len(png) // 1024}KB', flush=True)
        except Exception as e:
            print(f'{tid}: FAILED ({e})', file=sys.stderr, flush=True)
    out = {}
    for tid in SOURCES:
        p = os.path.join(STAGE, tid + '.png')
        if os.path.exists(p):
            with open(p, 'rb') as f:
                out[tid] = 'data:image/png;base64,' + base64.b64encode(f.read()).decode('ascii')
    js = ('/* ==========================================================================\n'
          '   trophy-imgs.js — GENERATED by tools/build-trophy-imgs.py. Do not edit.\n\n'
          '   Transparent PNG cut-outs of the real trophies, embedded as data URIs\n'
          '   (backgrounds removed locally with rembg from Wikimedia Commons\n'
          '   photographs — see js/trophies.js for sources and fallbacks).\n'
          '   ========================================================================== */\n'
          '(function (global) {\n'
          "  'use strict';\n"
          '  global.TROPHY_IMGS = ' + json.dumps(out) + ';\n'
          '})(window);\n')
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(js)
    print(f'js/trophy-imgs.js written — {len(out)} trophies, {os.path.getsize(OUT) // 1024}KB')


if __name__ == '__main__':
    main()
