#!/usr/bin/env python3
"""build-badge-imgs.py — generate js/badge-imgs.js

Downloads every club badge named in js/badges.js, trims transparent
margins, centres each crest on a square canvas at a crisp fixed height
and ships the lot as data URIs inside the game — no hotlink pop-in, no
broken links, uniform framing. Run from the repo root:

    .venv/Scripts/python tools/build-badge-imgs.py

Reuses the audit cache in .tmp-badges/all when the source URL matches
the earlier download; js/badges.js stays as the online fallback.
"""
import base64
import io
import json
import os
import re
import sys
import time
import urllib.request

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CACHE = os.path.join(ROOT, '.tmp-badges', 'all')
REPORT = os.path.join(ROOT, '.tmp-badges', 'report.json')
OUT = os.path.join(ROOT, 'js', 'badge-imgs.js')
UA = {'User-Agent': 'football-life-badge-builder/1.0 (personal game project)'}
HEIGHT = 144  # 2x+ the biggest display size (.crest-xl = 64px)


def slug(club):
    return re.sub(r'[^\w]+', '_', club)


def fetch(url):
    req = urllib.request.Request(url, headers=UA)
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read()


def load_badges():
    src = open(os.path.join(ROOT, 'js', 'badges.js'), encoding='utf-8').read()
    return json.loads(re.search(r'global\.BADGES = (\{[\s\S]*?\n\});', src).group(1))


def process(raw):
    img = Image.open(io.BytesIO(raw)).convert('RGBA')
    bbox = img.getchannel('A').getbbox()
    if bbox:
        img = img.crop(bbox)
    w, h = img.size
    pad = max(3, int(max(w, h) * 0.04))
    canvas = Image.new('RGBA', (w + pad * 2, h + pad * 2), (0, 0, 0, 0))
    canvas.paste(img, (pad, pad))
    ratio = HEIGHT / canvas.size[1]
    canvas = canvas.resize((max(1, round(canvas.size[0] * ratio)), HEIGHT), Image.LANCZOS)
    buf = io.BytesIO()
    canvas.save(buf, 'PNG', optimize=True)
    return canvas, buf.getvalue()


def main():
    badges = load_badges()
    old_report = {}
    if os.path.exists(REPORT):
        old_report = json.load(open(REPORT, encoding='utf-8'))
    os.makedirs(CACHE, exist_ok=True)
    out = {}
    for club, url in badges.items():
        path = os.path.join(CACHE, slug(club) + '.png')
        raw = None
        # reuse the audit download when the URL has not changed
        if os.path.exists(path) and old_report.get(club, {}).get('url') == url:
            raw = open(path, 'rb').read()
        for attempt in range(4):
            if raw:
                break
            try:
                raw = fetch(url)
                open(path, 'wb').write(raw)
                break
            except Exception as e:
                print(f'{club}: fetch retry ({e})', file=sys.stderr, flush=True)
                time.sleep(4 * (attempt + 1))
        if not raw:
            print(f'{club}: SKIPPED (download failed)', file=sys.stderr)
            continue
        try:
            img, png = process(raw)
            img.save(path)  # cache the trimmed version too
            out[club] = 'data:image/png;base64,' + base64.b64encode(png).decode('ascii')
            print(f'{club}: {len(png) // 1024}KB', flush=True)
        except Exception as e:
            print(f'{club}: FAILED ({e})', file=sys.stderr, flush=True)
        time.sleep(0.6)
    js = ('/* ==========================================================================\n'
          '   badge-imgs.js — GENERATED by tools/build-badge-imgs.py. Do not edit.\n\n'
          '   Trimmed, normalised transparent PNGs of every club badge, embedded\n'
          '   as data URIs so the game never waits on (or misses) a hotlink.\n'
          '   js/badges.js remains the online source list and fallback.\n'
          '   ========================================================================== */\n'
          '(function (global) {\n'
          "  'use strict';\n"
          '  global.BADGE_IMGS = ' + json.dumps(out, ensure_ascii=False) + ';\n'
          '})(window);\n')
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(js)
    print(f'js/badge-imgs.js written — {len(out)} badges, {os.path.getsize(OUT) // 1024}KB')


if __name__ == '__main__':
    main()
